// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotasG5.Models;

namespace NotasG5.Migrations
{
    [DbContext(typeof(NotasContext))]
    partial class NotasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("NotasG5.Models.Nota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreadorMail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CreadorMail");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("NotasG5.Models.Usuario", b =>
                {
                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mail");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NotasG5.Models.Nota", b =>
                {
                    b.HasOne("NotasG5.Models.Usuario", "Creador")
                        .WithMany("Notas")
                        .HasForeignKey("CreadorMail");
                });
#pragma warning restore 612, 618
        }
    }
}
